### PR TITLE
Updating subscribe params

### PR DESCRIPTION
**Pull request by jakearchibald**

### CODE REVIEW

**Comment by appsforartists** [comment]
@jakearchibald I think you've confused the Observer API and the positional API.

I believe `subscribe(next, error, complete)` and `subscribe({ next, error, complete })` are both being proposed; the latter interface (with the named arguments) is called an `Observer` and is already specified in the method above the one you've edited.  You can see the shape of `Observer` towards the bottom of the README.

**Comment by benjamingr** [comment]
@appsforartists this is just the argument names, so when you `.toString` it you get friendlier names in the reference implementation. Not an API change.

**Comment by jakearchibald** [comment]
@appsforartists you're right, I didn't realise that the positional was also supported.

Maybe the README could be updated to explain this? The definition of `.subscribe` suggests that only the positional form works, whereas all the examples use the observer form.

**Comment by appsforartists** [comment]
It would definitely be more clear if they introduced Observer before Observable.  I'm neither in TC39 nor an editor to this repo, so I have no expertise on spec text.  Maybe @jhusain would accept a PR changing the order?

**Comment by appsforartists** [comment]
@benjamingr I know positional argument names don't matter - just trying to help Jake understand the `subscribe` API.  😃

**Pull request closed without merging**
